// Shared sample content for all prototypes.
// AUTO-EXTRACTED from index.html — the chapter text, highlights (data-link) and image
// config here are the REAL ones from the live site, so a prototype is exercised with the
// true text heights. Image paths are prefixed with ../ (prototypes live one level down).
window.CHAPTERS = [
  {
    num: "I",
    title: "Beginnings and a Return",
    html: `
      <p>I have loved calligraphy since I was very young. when I was in primary school age, I would sit down and practice for about an hour every day, entirely on my own initiative. I never had a teacher—I simply practiced with <span class="hl" data-link="img_1_1">calligraphy model books</span> and taught myself. That went on for a few years.</p>
      <p>Later, my love for calligraphy naturally led me to <span class="hl" data-link="img_1_2">Chinese painting</span>. During every winter and summer break, I painted almost every day, and the walls of my home were covered with my work. This spontaneous fascination stayed with me until high school.</p>
      <p>In high school and later at university, my studies became more demanding, and both calligraphy and painting were set aside. Later, when I went abroad to study design in Sweden and then in Denmark, and eventually began working as a designer at LEGO, life turned out to be less busy than I had expected. With more free time after work, I returned to calligraphy. I began practicing again at home following the calligraphy model books.</p>
      <p>I was around twenty-seven or twenty-eight at the time, and this round of practice felt completely different from my childhood experience. Back then the practice was mostly mechanical, but as an adult I began to pay attention to brushwork, rhythm, and energy. I progressed quickly, and I kept up this practice for about a year or two.</p>
    `,
    images: [
      { id: "img_1_1", caption: "Calligraphy model books", label: "Self-taught", placeholder: "Model books", src: "../c1/1_model_books.jpg" },
      { id: "img_1_2", caption: "Chinese painting", label: "Painting", placeholder: "Chinese painting", src: "../c1/2_chinese_painting.jpg" }
    ]
  },
  {
    num: "II",
    title: "Large Character Calligraphy",
    html: `
      <p>During this period, I also read extensively about calligraphy—its history, lineage, theories, and the biographies of calligraphers. One book had a profound influence on me: <span class="hl" data-link="img_2_1"><i>Yu-ichi Inoue: The Calligraphy Is for Everyone</i></span>.</p>
      <p>Inoue Yuichi was a pioneer of modern Japanese calligraphy and played an important role in introducing it to the West. His work resonated with Western modern art movements of his time. What struck me the most, however, was not his historical contribution but his <span class="hl" data-link="img_2_2a img_2_2b">giant single-character works created with enormous brushes</span>. They carried both tradition and bold innovation.</p>
      <p>To be honest, I knew my foundation in traditional calligraphy wasn't yet solid enough, and it would be difficult for me to make real breakthroughs within its traditional framework. But Inoue Yuichi's practice opened a door for me. It made me realize that with a large brush, I might be able to create something powerful myself.</p>
      <p>So I began to shape my own artistic practice. The first step, was to have a <span class="hl" data-link="img_2_3">large brush custom-made</span> and to buy a lot of Xuan paper. Then I started <span class="hl" data-link="img_2_4a img_2_4b">looking for a studio. In the nearby city of Vejle, I found Spinderihallerne</span>, a former spinning mill that had been turned into a creative hub for start-ups, independent designers, and artists. I rented a small spot there—an open area of about three by three meters. Most people there worked regular office hours. I was almost the only one who came in after work and on weekends. That made it possible for me to make use of the large shared spaces. This proved crucial for my work. It allowed me to make large-scale work and later shaped my entire creative process in ways I did not yet understand.</p>
      <p><span class="hl" data-link="img_2_5a img_2_5b">The early attempts of my calligraphy work</span> were, strictly speaking, not really "authentic." They were closer to an imitation of Inoue Yuichi. The oversized brushes, the way I used the edges of the paper to slice through the character—although I felt I was trying many formal variations at the time, I still hadn't actually stepped outside the framework he had established. Most of my effort then was spent experimenting with materials and techniques, trying to feel my way forward.</p>
      <p>Writing with an oversized brush breaks the traditional paradigm. Traditional calligraphy is usually done on a desk, relying on the coordination of fingers and wrist to achieve different strokes. But once the characters grow to the scale of the body, you have to write on the floor, using your whole arm and even your whole body. So I had to develop an entirely new way of handling the brush that made sense for large characters.</p>
      <p>Controlling the ink was just as crucial. With a large brush, everything changes—the amount of ink you load, the speed of your strokes, the ratio of ink to water, and how different kinds of Xuan paper absorb and spread the ink. I had to rebuild my understanding of all of this from scratch. Otherwise, the result could easily turn into one dark, muddled blot.</p>
      <p>Around this time, another artist came into my view—<span class="hl" data-link="img_2_6">Wang Dongling</span>. He is also known for writing large characters, creating monumental works, and developing his own form called "chaos script." Beyond that, he made many new explorations in contemporary calligraphy. His focus on <span class="hl" data-link="img_2_7">cursive script</span> was especially significant to me. I felt an inherent connection between cursive writing and large-scale brushwork, and my intuition told me that big characters should be written in cursive.</p>
      <p>So I decisively shifted to writing in cursive and began studying it more systematically. Practice soon showed me that it not only made the writing feel more fluid, but also addressed a key issue of working with a large brush: the faster pace of cursive keeps the ink from spreading into a blot. Even if there was some pooling at the beginning of a stroke, the dry-brush effect that appeared as the ink thinned out created a striking contrast.</p>
      <p>Once I began <span class="hl" data-link="img_2_8a img_2_8b img_2_8c">writing large characters in cursive</span>, I could feel myself improving noticeably. I often slipped into a state of full concentration, finishing a piece in one continuous motion and feeling a clear sense of exhilaration. I also tried new approaches to structure and composition, and the writing as a whole began to feel more confident.</p>
    `,
    images: [
      { id: "img_2_1", caption: "Yu-ichi Inoue: The Calligraphy Is for Everyone", label: "Key influence", placeholder: "Inoue book", src: "../c2/1_book.jpg" },
      { id: "img_2_2a", caption: "Inoue writing process", label: "Process", placeholder: "Inoue writing", src: "../c2/2a_inoue_writing.jpg" },
      { id: "img_2_2b", caption: "Giant single-character works", label: "Innovation", placeholder: "Giant characters", src: "../c2/2b_inoue_work.jpg" },
      { id: "img_2_3", caption: "Large custom-made brush", label: "Tools", placeholder: "Large brush", src: "../c2/3_brushes.jpeg" },
      { id: "img_2_4a", caption: "Spinderihallerne studio in Vejle", label: "Workspace", placeholder: "Studio space", src: "../c2/4a_spinderi.jpg" },
      { id: "img_2_4b", caption: "Studio workspace setup", label: "Space", placeholder: "Studio setup", src: "../c2/4b_studio.jpeg" },
      { id: "img_2_5a", caption: "Early calligraphy attempts", label: "Learning", placeholder: "Early attempts", src: "../c2/5a_early_attemps.jpg" },
      { id: "img_2_5b", caption: "Early calligraphy practice", label: "Development", placeholder: "Early practice", src: "../c2/5b_early_attemps.jpg" },
      { id: "img_2_6", caption: "Wang Dongling \u2014 chaos script", label: "Inspiration", placeholder: "Wang Dongling", src: "../c2/6_wangdongling.jpg" },
      { id: "img_2_7", caption: "Cursive script Huaisu 737-799", label: "Cursive", placeholder: "Cursive script", src: "../c2/7_cursive.jpg" },
      { id: "img_2_8a", caption: "Cursive Calligraphy Work", label: "Cursive", placeholder: "Cursive script", src: "../c2/8a_early_calligraphy.jpeg" },
      { id: "img_2_8b", caption: "Cursive Calligraphy Work", label: "Cursive", placeholder: "Cursive script", src: "../c2/8b_early_calligraphy.jpg" },
      { id: "img_2_8c", caption: "Cursive Calligraphy Work", label: "Cursive", placeholder: "Cursive script", src: "../c2/8c_early_calligraphy.jpeg" }
    ]
  },
  {
    num: "III",
    title: "Line Works",
    html: `
      <p>Writing large characters in cursive requires an intense moment of focus, and a piece is usually finished within a few seconds, with no chance to revise. This immediacy is one of the reasons I love calligraphy. But working this way continuously is extremely demanding, both mentally and physically, so I began looking for another mode of working—one that didn't rely on sudden bursts of energy, but instead allowed me to settle into a slower, almost meditative pace.</p>
      <p>The first thing that came to mind was drawing lines. When I studied design, we often practiced basic horizontal and vertical lines in sketchbooks to build fundamental sketching skills. So I started using a small brush fully loaded with ink, <span class="hl" data-link="img_3_1">drawing lines on a large sheet of Xuan paper</span>. I began by drawing straight lines in <span class="hl" data-link="img_3_2">horizontal, vertical, and diagonal directions, and later I moved on to arcs</span>. Each time I loaded the brush with ink, I would draw one line and then repeat the same action right next to the previous line.</p>
      <p>This seemingly mechanical motion produced endlessly <span class="hl" data-link="img_3_3">varied gradations</span> as the ink slowly dried out. The repeated lines also opened up many possibilities for composition. Later, I began using masking, which expanded the complexity of the compositions even further. This was exciting for me, and I felt as if I had discovered a parallel creative path in my practice.</p>
      <p>This way of working seemed to echo my calligraphy practice: one was fast, the other slow; one required an intense, momentary focus, while the other called for a long, almost meditative concentration. One was active, the other still, and they complemented each other. Ultimately, both forms of practice helped me get to know the brush, the ink, and the Xuan paper more intimately, bringing me closer to a sense of ease with these tools and materials.</p>
      <p>As my exploration of lines continued, I no longer aimed to draw perfect straight lines or arcs. Instead, I began trying lines with <span class="hl" data-link="img_3_4">a freer, more organic form</span>, which gradually expanded the boundaries of the line series.</p>
    `,
    images: [
      { id: "img_3_1", caption: "Drawing lines on xuan paper", label: "Meditation", placeholder: "Meditative lines", src: "../c3/1_drawing_lines.jpg" },
      { id: "img_3_2", caption: "Drawing lines on xuan paper", label: "Practice", placeholder: "Line drawing", src: "../c3/2_shapes.jpg" },
      { id: "img_3_3", caption: "Endlessly shifting gradations", label: "Variations", placeholder: "Ink gradations", src: "../c3/3_details.jpg" },
      { id: "img_3_4", caption: "Movement and stillness", label: "Balance", placeholder: "Balance forms", src: "../c3/4_form.jpg" }
    ]
  },
  {
    num: "IV",
    title: "Bottlenecks and Reflection",
    html: `
      <p>This period of exploring calligraphy and line work lasted for nearly three years. Looking back now, I see it as a crucial stage of accumulation in my artistic practice. I produced many studies, a few pieces I was genuinely happy with, and <span class="hl" data-link="img_4_1">a large number of failed attempts</span> as well.</p>
      <p>As I continued to repeat the process, certain limitations began to surface, and I started questioning the meaning of what I was doing, especially the large-character calligraphy. Although the line-based work carried a degree of innovation, after a long period of experimentation I found myself approached the compositional boundaries. If I continued in the same way, similarity and repetition would become inevitable.</p>
      <p>The situation with my calligraphy was even less encouraging. I began to feel that I had never really stepped out of the shadows of Inoue Yuichi and Wang Dongling. And the act of enlarging characters itself had become such a familiar formula in contemporary calligraphy that it no longer felt new. Since Inoue, countless people had tried to follow the same path, and in today's context it can hardly be called innovative at all.</p>
      <p>I also began to notice works that felt more like performances than calligraphy. Without much engagement with tradition, some artists simply <span class="hl" data-link="img_4_2">scaled up the brush and the paper to a point where the body could barely control them</span>, turning the whole act into something meant to impress. It felt far from what I understood calligraphy to be.</p>
      <p>When I looked back at my own work, I realized I hadn't really escaped the influence of contemporary calligraphy practice I was surrounded by, and true originality still felt out of reach. And if that was the case, then what was the point of my writing at all? These questions started to surface quietly, nudging me to face the difficulties within my own practice.</p>
    `,
    images: [
      { id: "img_4_1", caption: "Failed attempts \u2014 accumulation", label: "Accumulation", placeholder: "Failed attempts" },
      { id: "img_4_2", caption: "Shadows of Inoue Yuichi and Wang Dongling", label: "Limitations", placeholder: "Shadows of influence", src: "../c4/2_performance.jpg" }
    ]
  },
  {
    num: "V",
    title: "The Turning Point: Collage",
    html: `
      <p>After a period of reflection, I realized that I needed to look for something more distinct in my artistic practice, even though I didn't yet know what that might be. Looking back now, I can see that a key moment came later, when I took part in a collage workshop hosted by an artist, where we created images using piles of discarded magazines.</p>
      <p>I had never tried collage before. In my mind, it was a form that leaned too much toward literal imagery and often carried a Pop Art sensibility, which didn't really speak to me. So I simply never found myself engaging with it.</p>
      <p>The workshop offered a wide range of documentary photographs, many of which carried a strong visual and social tension. Although I had never worked with collage before, I soon realized that the process came naturally to me. Faced with piles of unrelated images, I could sense small visual or thematic echoes almost immediately, then cut and piece them together into something new, creating a sharp visual shift or a twist in meaning.</p>
      <p>Within about two hours, I made <span class="hl" data-link="img_5_1">nearly ten pieces. Each was a simple collage made from just two images</span>, yet both the content and the visual quality felt deeply satisfying. After the workshop, I sensed that I had unlocked a new skill, although I didn't realize how much it would impact my creative path later. Collage made from magazine images felt distant from my ink-based practice, and at the time it was hard to imagine how the two might connect.</p>
      <p>After the workshop, I returned to my normal work routine. It wasn't until some time later that I had to face the large number of <span class="hl" data-link="img_5_2">failed calligraphy and line pieces</span> that had accumulated over the years. They were gradually taking over my studio, and I either needed a bigger space or had to find a way to deal with them.</p>
      <p>As I remember in that book about Inoue Yuichi, he would simply burn all the works he was unsatisfied with in his backyard. I once had the same impulse—to burn everything and start again. But then a small thought sparked in me: wasn't I good at piecing things together into a collage? Why not cut these so-called failed pieces apart and reassemble them into something new? Perhaps there was a hidden possibility there.</p>
      <p>I started with the line pieces, since they had a certain level of consistency in form, and my intuition told me that they would be easier to reshape into new compositions. I spread a large number of discarded line works across the floor, looking closely at them and considering which combinations of the pieces might give them a new life.</p>
      <p>This was my first time making collages out of my own materials, and the first attempt went surprisingly smoothly. Within a short time, three or four pieces took shape that I felt genuinely satisfied with. Following the same approach, I soon created the <span class="hl" data-link="img_5_3">first group of line collages</span>.</p>
      <p>I continued to develop the line collages, trying different approaches based on the materials at hand. The whole process felt unexpectedly fluid. Looking back now, it was likely because the textures of the line pieces were relatively consistent, making it easier for them to merge with one another, and I soon produced a large number of works in this series.</p>
      <p>This period of practice also gave me greater confidence in the collage technique. I felt that a new direction was opening up in my art. I ended up using almost all of my failed line pieces, until there was hardly any material left to work with. At that point, a natural thought emerged: if I could make the line collages work, then in theory, <span class="hl" data-link="img_5_4">calligraphy pieces could be reworked through the same approach</span>.</p>
      <p>But the analogy is not entirely accurate. An assembly line produces identical outcomes, while this process kept generating its own quiet surprises, producing works that stayed within a coherent style yet gradually broadened the scope of my visual language. To see whether the method could reach beyond its original context, I began experimenting with combining line pieces with calligraphy and also created various kinds of ink-wash material for collage. These experiments showed that each direction had the potential to unfold.</p>
    `,
    images: [
      { id: "img_5_1", caption: "Collage workshop \u2014 the turning point", label: "Discovery", placeholder: "Collage workshop" },
      { id: "img_5_2", caption: "Failed pieces become raw material", label: "Transformation", placeholder: "Raw material" },
      { id: "img_5_3", caption: "First line collages", label: "New direction", placeholder: "Line collages" },
      { id: "img_5_4", caption: "Moving from line to calligraphy collage", label: "Evolution", placeholder: "Calligraphy collage" }
    ]
  },
  {
    num: "VI",
    title: "Calligraphy Collage: Exploration and Methodology",
    html: `
      <p>So I returned to the method I had developed and spread more calligraphy fragments across the studio floor, trying to see how they might relate. With the openness of the shared studio space, I could finally lay out a large amount of material at once and observe the relationships among them as a whole.</p>
      <p>The first attempts were not as smooth as the line collages, although that didn't really surprise me. Calligraphy, especially cursive script, has a much more open structure, with denser overlaps and more difficult choices to make. I had a tendency to see the marks as written characters, and it took time to set that aside and <span class="hl" data-link="img_6_1">treat them simply as images</span>.</p>
      <p>Although the initial process was extremely challenging, I also came to realize that compared with the line collages, calligraphy offered far greater freedom and many more possibilities, along with a higher level of difficulty. I believed that with enough time and exploration, I would eventually find a way into this way of working and let the process unfold more smoothly.</p>
      <p>In the phase that followed, my work with calligraphy collage took much longer to find its rhythm. The process shifted constantly between ease and difficulty. Some days I could complete several pieces, while on other days I felt completely stuck, unable to move forward. It became clear that calligraphy collage was far more complex than the line collage work. With the line pieces, two or three separate elements were often enough to create a strong visual impact and a complete composition. Calligraphy collage, by contrast, felt like something that had to <span class="hl" data-link="img_6_2">grow outward from a small fragment</span>. It needed more elements, more layers of overlap, and many more rounds of trial and adjustment before the image could settle and the work finally take shape.</p>
      <p>After a long period of exploration, I gradually began to form a clearer sense of the methods, ideas, and techniques that supported this way of working. One of the first abilities I developed was a sharp intuition for <span class="hl" data-link="img_6_3">which visual elements held the most potential</span>, whether they were single strokes or small fragments. I had to separate them decisively with a knife. This step was crucial, because it shaped the level of difficulty in everything that followed. Yet the decision itself was almost entirely intuitive, built through repeated practice, and not really a matter of right or wrong.</p>
      <p>I usually prepare part of the material in advance, cutting as many usable fragments as I can from each piece of calligraphy. Once I feel there are enough elements to work with, I begin the actual collage. I found that if I prepare too much material at once, the number of possible combinations grows almost exponentially. Rather than giving me more options, it makes the process far more difficult, and I struggle to make quick decisions with so many possibilities open in front of me.</p>
      <p>Each time I begin a collage, I first mark out the approximate size of the piece on a sheet of white paper laid over cardboard. This prevents the work from expanding endlessly and becoming difficult to contain. It may seem like a constraint, but it forces me to search for the <span class="hl" data-link="img_6_4">perfect fragment that fits the scale of the work</span> and completes the missing part of the puzzle.</p>
      <p>In terms of composition, I also began to recognize certain internal impulses within the collage process. For instance, I often found myself instinctively following the calligraphic idea of <span class="hl" data-link="img_6_5">strokes that appear broken on the paper but are carried by a continuous movement</span>. Even when the fragments came from unrelated sources, I still hoped that once assembled, they would carry a sense of flow and rhythm consistent with the structure of cursive script.</p>
      <p>Another impulse that excited me was the search for those rare, <span class="hl" data-link="img_6_6">accidental moments of correspondence</span>. Two fragments might come from different periods or entirely different works, yet when placed together they could fit so seamlessly that they even created a kind of visual illusion, as if they had always belonged to one another. It requires great patience and a bit of luck, but whenever such a coincidence appears, I feel a clear sense of creative satisfaction.</p>
      <p>The calligraphy collages became the body of work I engaged with most deeply, spanning nearly three to four years of exploration and practice. The first batch of writing material was used up quickly, and after that I produced several more rounds of large cursive writing. It was less about creating finished pieces and more a kind of daily "copying" practice. But even the word "copying" is not quite accurate, since copying in the traditional sense aims at imitation, and this kind of large-scale calligraphy has no model to follow in the first place.</p>
      <p>It reminded me of Wang Duo's work. Many of his scrolls grew out of his daily "copying" practice, yet he never aimed for likeness. Instead, he allowed those exercises to merge naturally into a powerful personal style. With that in mind, I immersed myself in Wang Xizhi's <i>The Seventeen Letters</i> as my model book, studying it with focus and using it as the basis for my own form of "copying."</p>
      <p>This shift naturally changed my motivation for writing large characters. Earlier, my writing was driven by the desire to create, with the hope that each piece might become something final. Later, the writing became simply part of my daily practice, and I no longer carried any expectations for the result. This gave the act of writing a greater sense of purity, almost like returning to my childhood, when I practiced calligraphy simply out of love for it. And as a kind of by-product, this daily writing produced a great deal of material for the next stage of my collage work.</p>
      <p>At this point, I began to realize that an entirely new working process was taking shape. The daily practice of writing large characters had become the preparatory stage for generating collage material. It was almost completely separate from the collage work that followed. What first felt like a disconnect ended up freeing my writing in an unexpected way. The act of writing no longer carried any intention of making a finished piece, but existed simply for the sake of writing itself.</p>
      <p>Even the quality of the writing, whether it turned out well or poorly, was no longer something to be criticized, since both the successful strokes and the failed ones would eventually find their place within the collage. The process became something closer to assembling a puzzle, requiring considerable patience and a keen sensitivity to form and image, searching through a wide field of material for moments that seem almost accidental yet somehow inevitable. And the results continued to offer surprises, as the finished collages often moved beyond the limits of my own visual language.</p>
      <p>This process applied just as well to the line series. I began to abstract and clarify the steps involved, which eventually formed a simple working sequence: preparing material without any creative intention, piecing it together following a logic I had established, and allowing the finished work to emerge. The process began to function almost like an assembly line, with each step contributing to steady production.</p>
    `,
    images: [
      { id: "img_6_1", caption: "Seeing calligraphy as image", label: "Perspective", placeholder: "Calligraphy as image" },
      { id: "img_6_2", caption: "Growing outward from a small fragment", label: "Process", placeholder: "Growing fragments" },
      { id: "img_6_3", caption: "Cutting fragments \u2014 intuition for potential", label: "Intuition", placeholder: "Cutting fragments" },
      { id: "img_6_4", caption: "Perfect fragment that fits the scale", label: "Precision", placeholder: "Perfect fit" },
      { id: "img_6_5", caption: "Broken strokes carried by continuous movement", label: "Flow", placeholder: "Continuous movement" },
      { id: "img_6_6", caption: "Accidental correspondence between fragments", label: "Serendipity", placeholder: "Accidental harmony" }
    ]
  },
  {
    num: "VII",
    title: "Meaning of Calligraphy Collage and Future Directions",
    html: `
      <p>After all these experiments, I found that my heart still followed the calligraphy collages. My work is rooted in calligraphy, and it is the starting point of all my artistic practice. Calligraphy, especially cursive script, carries a natural expressive strength that makes it an ideal source for collage. The discipline inherent in the act of writing allows the finished work to hold together with a coherent character, while the endless variations created by overlapping strokes introduce shifts and small surprises that shape the outcome of each piece.</p>
      <p>After all these experiments, calligraphy collage remains my favorite, and my heart still follows it. My work is rooted in calligraphy, and it is the starting point of all my artistic practice. Calligraphy, especially cursive script, carries a natural expressive strength that makes it an ideal source for collage. The discipline inherent in the act of writing gives the finished piece a coherent character, while the endless variations created by overlapping strokes introduce shifts and surprises that shape the outcome of each work.</p>
      <p>Calligraphy collage also responds to my reflections on contemporary calligraphy practice. Through physical cutting, <span class="hl" data-link="img_7_1">it breaks open the traditional structure</span>, and through reassembly, <span class="hl" data-link="img_7_2">it brings calligraphy into the field of contemporary art</span>. The strokes and lines within these collages carry the meaning of cultural symbols, and at the same time move toward the realm of Western abstraction. The overlapping layers create a sense of spatial depth. They bring a new dimension to what is otherwise a flat form of line art. For me, it opens a direction that feels genuinely innovative.</p>
      <p>Calligraphy, by its nature, is immediate and irreversible, whereas collage is a long process that involves continual adjustment, is time-consuming, and demands repeated consideration. Bringing these two contrasting processes together creates a practice that feels <span class="hl" data-link="img_7_3">conceptually intriguing</span> to me.</p>
      <p>At last, bringing collage into my practice also dissolved the usual way of evaluating calligraphy. Calligraphy became simply writing. It felt closer to how people in the past wrote their daily letters, never imagining that those casual notes would one day be regarded as masterpieces of art. The large cursive characters became part of my daily writing. Of course, steady practice leads to improvement, but the quality of any single session, whether good or bad, no longer had much impact on the collage work that followed. <span class="hl" data-link="img_7_4">Writing, in this sense, became pure.</span></p>
      <p>Although calligraphy collage is the direction I have worked for the longest period of time, I know clearly that I have not yet uncovered its full potential. It is a path that can still grow in depth and also branch into new directions.</p>
      <p>This once again confirmed that the working process I established is reliable. It allows me to produce work consistently, and it can extend into other mediums. Recently, I have also begun thinking about new motifs. One direction I feel particularly drawn to is bringing <span class="hl" data-link="img_7_5">Chinese painting into my collage vocabulary</span>, since it was an important part of my early artistic journey. Although I have not yet put this idea into practice, I remain curious about the process and the results it might lead to. Perhaps it will become another important piece in the larger picture of my artistic exploration.</p>
    `,
    images: [
      { id: "img_7_1", caption: "Breaking open the traditional structure", label: "Innovation", placeholder: "Breaking tradition" },
      { id: "img_7_2", caption: "Calligraphy in the field of contemporary art", label: "Context", placeholder: "Contemporary art" },
      { id: "img_7_3", caption: "Conceptually intriguing practice", label: "Concept", placeholder: "Conceptual practice" },
      { id: "img_7_4", caption: "Writing becomes pure", label: "Purity", placeholder: "Pure writing" },
      { id: "img_7_5", caption: "Chinese painting in collage vocabulary", label: "Future", placeholder: "Chinese painting" }
    ]
  }
];
